// Vida+ app.js v5.1.6
const supabase = window.supabase.createClient(window.SUPABASE_URL, window.SUPABASE_ANON_KEY);
const $=(q)=>document.querySelector(q);
const fmtDate=(d)=>{const z=new Date(d);const y=z.getFullYear();const m=('0'+(z.getMonth()+1)).slice(-2);const dd=('0'+z.getDate()).slice(-2);return `${y}-${m}-${dd}`;};
const todayStr=()=>fmtDate(new Date());
function setTopBar(score=0,streak=0){$('#scoreTop').textContent=isNaN(score)?'—':String(score);const dt=new Date();const meses=['jan','fev','mar','abr','mai','jun','jul','ago','set','out','nov','dez'];const dias=['dom','seg','ter','qua','qui','sex','sáb'];$('#dateTop').textContent=`${('0'+dt.getDate()).slice(-2)}/${meses[dt.getMonth()]} (${dias[dt.getDay()]})`;$('#streakNum').textContent=streak||0;}
async function ensureAuthUI(){const {data:{session}}=await supabase.auth.getSession();if(session&&session.user){$('#loginWrap').style.display='none';$('#content').style.display='grid';}else{$('#loginWrap').style.display='block';$('#content').style.display='none';}}
async function signIn(email,password){const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;}
async function signUp(email,password){const {error}=await supabase.auth.signUp({email,password});if(error)throw error;}
async function resetPass(email){const url=location.origin+location.pathname;const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:url});if(error)throw error;}
async function upsertTodayDummy(){const user=(await supabase.auth.getUser()).data.user;if(!user)throw new Error('Sem usuário autenticado');const payload={user_id:user.id,date:todayStr(),data:{score:Math.floor(50+Math.random()*50)}};const {error}=await supabase.from('days').upsert(payload,{onConflict:'user_id,date'}).select();if(error)throw error;return payload;}
async function fetchAllDays(){const user=(await supabase.auth.getUser()).data.user;if(!user)throw new Error('Sem usuário autenticado');const {data,error}=await supabase.from('days').select('date,data,updated_at').eq('user_id',user.id).order('date',{ascending:true});if(error)throw error;return data||[];}
function downloadCSV(rows){if(!rows||!rows.length){alert('Sem dados para exportar.');return;}const header=['date','score','updated_at'];const lines=[header.join(',')];for(const r of rows){const score=(r.data&&typeof r.data.score!=='undefined')?r.data.score:'';lines.push([r.date,score,r.updated_at||''].join(','));}const blob=new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='vida_plus.csv';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}
function diag(msg){const el=$('#diagLog');el.textContent+=(el.textContent?'\n':'')+msg;console.log('[DIAG]',msg);}
async function runDiag(){$('#diagLog').textContent='';diag('Iniciando diagnóstico...');try{diag('SDK ok. URL='+window.SUPABASE_URL);}catch(e){diag('Falha ao carregar SDK: '+e.message);return;}try{const u=(await supabase.auth.getUser()).data.user;diag('Usuário: '+(u?u.email:'(não logado)'));if(!u)throw new Error('Não logado');}catch(e){diag('ERRO getUser: '+e.message);return;}try{const p=await upsertTodayDummy();diag('UPSERT ok: '+JSON.stringify(p));}catch(e){diag('ERRO upsert: '+(e.message||e));console.error(e);return;}try{const rows=await fetchAllDays();diag('SELECT ok: '+rows.length+' linhas.');}catch(e){diag('ERRO select: '+(e.message||e));console.error(e);return;}diag('Diagnóstico concluído ✅');}
document.addEventListener('DOMContentLoaded',async()=>{setTopBar(0,0);await ensureAuthUI();supabase.auth.onAuthStateChange(async()=>{await ensureAuthUI();});$('#btnSignIn')?.addEventListener('click',async()=>{const email=$('#loginEmail').value.trim();const pass=$('#loginPass').value;$('#loginMsg').textContent='...';try{await signIn(email,pass);$('#loginMsg').textContent='Autenticado!';}catch(e){$('#loginMsg').textContent='Erro: '+(e.message||e);}});$('#btnSignUp')?.addEventListener('click',async()=>{const email=$('#loginEmail').value.trim();const pass=$('#loginPass').value;$('#loginMsg').textContent='...';try{await signUp(email,pass);$('#loginMsg').textContent='Conta criada. Faça login.';}catch(e){$('#loginMsg').textContent='Erro: '+(e.message||e);}});$('#btnReset')?.addEventListener('click',async()=>{const email=$('#loginEmail').value.trim();$('#loginMsg').textContent='...';try{await resetPass(email);$('#loginMsg').textContent='Email de redefinição enviado.';}catch(e){$('#loginMsg').textContent='Erro: '+(e.message||e);}});$('#btnDiag')?.addEventListener('click',runDiag);$('#btnExport')?.addEventListener('click',async()=>{try{const rows=await fetchAllDays();downloadCSV(rows);}catch(e){alert('Erro ao exportar: '+(e.message||e));}});$('#btnSignOut')?.addEventListener('click',async()=>{await supabase.auth.signOut();location.reload();});});
